name: Fetch Semgrep Findings (Artifact)

on:
  workflow_dispatch: {}  # run manually
  schedule:
    - cron: '45 2 * * *'  # run daily at 02:45 UTC
  push:
      branches:
        - main
        - master
      paths:
        - .github/workflows/workflow.yml
jobs:
  fetch-and-archive:
    runs-on: ubuntu-latest
    env:
      SEMGREP_API_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install requests python-dateutil

      - name: Run script to fetch Semgrep findings
        run: python findings.py

      - name: Upload findings as GitHub Actions artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-findings
          path: semgrep_findings.json
