name: Fetch Semgrep Rules

on:
  workflow_dispatch: {}  # Run manually from GitHub UI
  schedule:
    - cron: '42 18 * * *'  # Run daily at 18:42 UTC
  push:
      branches:
        - main
        - master
      paths:
        - .github/workflows/workflow.yml
jobs:
  fetch-rules:
    runs-on: ubuntu-latest
    env:
      SEMGREP_API_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests library
        run: pip install requests

      - name: Run fetch_rules.py
        run: python fetch_rules.py
